[transport.spread]
enabled=1
host=localhost
port=4803

[errorhandling]
onhandlererror = LOG

[spread.converter.cpp]
image = IplImage

[plugins.cpp]
path = C:\\opt\\rsb.spread-0.11\\x64\\vc12\\release\\bin
load = rsbspread    

[transport.socket]
enabled=0
host=localhost
port=5555
server=1